### PR TITLE
Fix recommended page highlight

### LINKED ISSUE #620: Recommend game page item style
In the recommend game page only the first game can apply the style.
image

### PR DESCRIPTION
**Pull request by candela97**
Fix #620
You may need to activate some options under "Tag" to trigger the issue.
The original fix was to add checks for discounted prices, but for the top highlight section I found there're several different styles:
https://store.steampowered.com/recommended/morelike/app/1016960/
https://store.steampowered.com/recommended/friendactivity/
https://store.steampowered.com/recommended/
So I made the tags appear right above the title instead, which covers all cases above.

Example of default style on owned games:

### CODE REVIEW

File: js/content/common.js [hunk 1]
```diff
@@ -1484,35 +1480,23 @@ let Highlights = (function(){
...
-                if (document.querySelector(".game_purchase_action")) {
-                    tags.style.float = "left";
-                    let node = root.querySelector(".game_purchase_action");
-                    node.insertAdjacentElement("beforebegin", tags);
-                    HTML.beforeBegin(node, '<div style="clear: right;"></div>');
+            else if (node.classList.contains("recommendation_highlight")) {
+                node.querySelector(".highlight_description").insertAdjacentElement("afterbegin", tags);
+            }
+            else if (node.classList.contains("similar_grid_item")) {
+                if (node.querySelector(".regular_price")) {
```
Comment (candela97) [inline js/content/common.js]: I realized I could just query both nodes instead of checking if either exists, will address this along with other suggestions!

File: js/content/common.js [hunk 2]
```diff
@@ -1467,12 +1467,8 @@ let Highlights = (function(){
             else if (node.classList.contains("small_cap")) {
```
Comment (candela97) [inline js/content/common.js]: This is for the "More Like This" section on app pages. There's not much space for tags and it's already obscuring the title. Perhaps remove this?
註解 2019-11-18 053836

Comment (MxtOUT) [reply js/content/common.js]: Yeah, why not
