### PR TITLE
FInventoryMarketHelper: Fix set background option

### LINKED ISSUE #1021: [BUG] "Set as Background" in Inventory no longer works
### Actual Behavior
As title. I think this was broken along with the update to profile edit options last summer.

### Desired Behavior
The new API endpoints are:
`https://api.steampowered.com/IPlayerService/SetEquippedProfileItemFlags/v1?access_token=`
`https://api.steampowered.com/IPlayerService/SetProfileBackground/v1?access_token=`

`webapi_token` can be retrieved from the page, but looks like the input needs to be encoded.

### PR DESCRIPTION
**Pull request by candela97**
Fixes #1021

### CODE REVIEW

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js [hunk 1]
```diff
@@ -152,70 +152,88 @@ export default class FInventoryMarketHelper extends Feature {
...
+            } catch (err) {
+                console.error(err);
+                return;
+            }
+        }
+
+        // Loop through owned backgrounds to find the communityitemid for selected background
+        if (!thisItem.dataset.communityitemid) {
+
+            const m = viewFullBtn.href.match(/items\/\d+\/.+\.jpg/);
```
Comment (candela97) [inline src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:189]: Are preview images always in `.jpg`?

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js [hunk 2]
```diff
@@ -152,70 +152,88 @@ export default class FInventoryMarketHelper extends Feature {
...
+            formData.append("communityitemid", thisItem.dataset.communityitemid);
 
-            // Make sure the background we are trying to set is not set already
-            const m = result.match(/SetCurrentBackground\( {"communityitemid":"(\d+)"/i);
-            const currentBg = m ? m[1] : false;
+            try {
+                await Promise.all([
+                    RequestData.post(`https://api.steampowered.com/IPlayerService/SetProfileBackground/v1?access_token=${this.userToken}`, formData, {"credentials": "omit"}),
+                    RequestData.post(`https://api.steampowered.com/IPlayerService/SetEquippedProfileItemFlags/v1?access_token=${this.userToken}`, formData, {"credentials": "omit"})
+                ]);
```
Comment (candela97) [inline src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:229]: Not sure if the order matters.

Comment (Revadike) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:229]: It does not. The whole point of `Promise.all` is to run promises concurrently/simultaneously and wait for them all to finish.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 1 above)
Comment (Revadike) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:189]: Perhaps its better to be more flexible with the extension.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js [hunk 3]
```diff
@@ -152,70 +152,88 @@ export default class FInventoryMarketHelper extends Feature {
...
         const viewFullBtn = itemActions.querySelector("a");
-        if (!viewFullBtn) { return; }
+        if (!viewFullBtn || !/public\/images\/items/.test(viewFullBtn.href)) { return; }
 
-        if (!/public\/images\/items/.test(viewFullBtn.href)) { return; }
+        // Get owned backgrounds and the communityitemid for equipped background
+        if (!this.profileBgsOwned) {
+
+            // Retrieve access token from user's profile to use in Steam API calls
+            const html = await RequestData.getHttp(User.profileUrl);
```
Comment (MxtOUT) [inline src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:167]: Can't this be included in `Promise.all`?

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js [hunk 4]
```diff
@@ -152,70 +152,88 @@ export default class FInventoryMarketHelper extends Feature {
...
-    _setBackgroundOption(thisItem, assetId, itemActions) {
+    async _setBackgroundOption(thisItem, itemActions) {
 
-        if (!document.querySelector(".inventory_links")) { return; }
         if (itemActions.querySelector(".es_set_background")) { return; }
 
+        // Make sure the selected item is a background
         const viewFullBtn = itemActions.querySelector("a");
-        if (!viewFullBtn) { return; }
+        if (!viewFullBtn || !/public\/images\/items/.test(viewFullBtn.href)) { return; }
```
Comment (MxtOUT) [inline src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:161]:
```suggestion
        if (!viewFullBtn || !viewFullBtn.href.includes("public/images/items")) { return; }
```

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 1 above)
Comment (MxtOUT) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:189]: Then maybe remove the extension part from the regex?

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js [hunk 5]
```diff
@@ -152,70 +152,88 @@ export default class FInventoryMarketHelper extends Feature {
...
+
+            // Retrieve access token from user's profile to use in Steam API calls
+            const html = await RequestData.getHttp(User.profileUrl);
+            const dummyPage = HTMLParser.htmlToDOM(html);
+            const config = dummyPage.getElementById("application_config").dataset.loyaltystore;
+            this.userToken = JSON.parse(config).webapi_token;
+
+            try {
+                const [equipped, owned] = await Promise.all([
+                    RequestData.getJson(`https://api.steampowered.com/IPlayerService/GetProfileItemsEquipped/v1?access_token=${this.userToken}&steamid=${User.steamId}`, {"credentials": "omit"}),
```
Comment (MxtOUT) [inline src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:174]: Is it worth it to fetch this just to prevent setting it again?

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js [hunk 6]
```diff
@@ -152,70 +152,88 @@ export default class FInventoryMarketHelper extends Feature {
...
+            const formData = new FormData();
+            formData.append("communityitemid", thisItem.dataset.communityitemid);
 
-            // Make sure the background we are trying to set is not set already
-            const m = result.match(/SetCurrentBackground\( {"communityitemid":"(\d+)"/i);
-            const currentBg = m ? m[1] : false;
+            try {
+                await Promise.all([
+                    RequestData.post(`https://api.steampowered.com/IPlayerService/SetProfileBackground/v1?access_token=${this.userToken}`, formData, {"credentials": "omit"}),
+                    RequestData.post(`https://api.steampowered.com/IPlayerService/SetEquippedProfileItemFlags/v1?access_token=${this.userToken}`, formData, {"credentials": "omit"})
```
Comment (MxtOUT) [inline src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:228]: What does this endpoint do?

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 2 above)
Comment (candela97) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:229]: I was wondering if these calls depended on each other in some way, turns out they don't.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 4 above)
Comment (candela97) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js]: Fixed along with removing the extension part from the regex to match background urls.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 5 above)
Comment (candela97) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:176]: Currently we disable the button to indicate the background has been successfully changed, so I think it makes sense to also disable the button if the background had been set already.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 6 above)
Comment (candela97) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:229]: It seems to set the equip options for the background (like on your profile edit page, original size or full screen). Should we present these options to users? If not it can probably be removed.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 3 above)
Comment (candela97) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:169]: Can it? The user token is required to make those API calls, they can't be done at the same time.
Also what do you think of moving this to background, or the User class, so it can be called like `User.getUserToken()`? See https://github.com/tfedor/AugmentedSteam/issues/1021#issuecomment-769078402.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 5 above)
Comment (MxtOUT) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:176]: But this check is performed when a user clicks on the button, not before.
Also, if we unconditionally set the background, the button will be disabled anyway.

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 6 above)
Comment (MxtOUT) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:229]: Seems like a good idea to give those options to the user.
But it's not something this PR should add, so it's best to remove it for now

File: src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js (hunk 5 above)
Comment (candela97) [reply src/js/Content/Features/Community/Inventory/FInventoryMarketHelper.js:176]: It is also checked before inserting the button HTML: https://github.com/tfedor/AugmentedSteam/pull/1023/files#diff-34841fbfcec4ea7f01d735611484ec226141c8d96addbb173a3411cb44466a69R203-R204, so if the selected backgound is currently equipped, the button won't be clickable. IMO this is better than the old behaviour, it feels odd if I equip a background, reload the inventory and the button is clickable again.
